# Generated by Django 3.2.16 on 2022-10-30 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('post_caption', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
